create database mydatabase;
use mydatabase;
select * from mytable limit 5;

#Q1. What is the Total revanue generated by male customers vs. female customer?
select gender, sum(purchase_amount) as revenue 
from mytable 
group by gender; 

#Q2. Which customers used a discound but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from mytable
where discount_applied = 'Yes' and purchase_amount >= (select avg(purchase_amount) from mytable);

#Q3. Which are the top 5 products with the highest review rating?
select item_purchased, round(avg(review_rating),2) as "Avg review rating"
from mytable 
group by item_purchased
order by avg(review_rating) desc
limit 5;


#Q4. Compare the avg purchase amount between standerd and express shipping 
select shipping_type,
round(avg(purchase_amount),2)
from mytable 
where shipping_type in ("Standard","Express")
group by shipping_type;

#@5. Do subscribe customer spend more? Compare average spend and total revenue between subscribers and non- subscribers
select subscription_status,
count(customer_id),
avg(purchase_amount),
sum(purchase_amount)
from mytable 
group by subscription_status;

#Q6. Which 5 products have the highest percentage of purchase with discount applied ?
select item_purchased, 
round(100* sum(case when discount_applied = 'Yes'Then 1 else 0 end)/count(*),2) as discount_rate
from mytable 
group by item_purchased
order by discount_rate desc
limit 5;

#Q7. Segment customer into new, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment?
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then "New"
    when previous_purchases between 2 and 10 then "returning"
    else "Loyal"
    end as customer_segment
from mytable
)
select customer_segment, count(*) as "number of customers"
from customer_type
group by customer_segment;

#Q8. What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from mytable
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

#Q9. Are customers who are repeat buyers (more than 5 previous purchases) also like to subscribe 
select subscription_status, Count(customer_id) as repeat_buyers 
from mytable
where previous_purchases > 5
group by subscription_status;

#Q10. What is the revanue contribution of each age group
select age_group ,sum(purchase_amount)as total_revanue from mytable
group by age_group
order by total_revanue desc;
